### PR TITLE
Fail-Fast: Assure termination of test script, if server cannot be built

### PR DESCRIPTION
**Pull request by ChristophKnabe**
**Problem solved**: The command `./runTests.sh inrupt-pod-server` failed repeatedly when requesting something from the Inrupt POD server. Each request had to wait until timeout. The cause was that the Inrupt POD server could not be created.
Here a fail-fast strategy helps. With the modification in the PR the script `runTests.sh` stops immediately after the messages `Step 4/13 : RUN git checkout dev
 ---> Running in ca0d14ea4085
error: pathspec 'dev' did not match any file(s) known to git.`
Now the absence of branch `dev` in the Inrupt POD server becomes immediately obvious.

### CODE REVIEW

**Comment by ChristophKnabe** [comment]
Having gone on with testing the Solid Test Suite I noticed, that I had to manually execute `docker stop server` and `docker rm server` each time after the `runTests.sh` script failed.
I would like to implement a proper cleanup, that means stop and remove a container, if it was successfully started.
Another modification needed would be to make the usage of `bash` explicit, as the script does not run on Ubuntu, which uses `dash` by default.

**Comment by kjetilk** [comment]
OK! I don't know much about Docker, so help in that area is welcome! @michielbdejong has done most of the work on that up to now, so his view would be nice to have.

**Comment by kjetilk** [comment]
OK, great! I merged this, further contributions are most welcome!

**Comment by ChristophKnabe** [comment]
Thanks for your positive feedback. I already prepared another PR, as I refactored the test script, see there.

**Pull request merged**
