### PR TITLE
Include new RDF-formulated HTTP tests

### PR DESCRIPTION
**Pull request by kjetilk**
This should be all that is needed to run the new tests. It means simply pick up all test runners in a directory.

### CODE REVIEW

**Comment by michielbdejong** [comment]
@kjetilk can you update the readme to show the new output table?

**Comment by kjetilk** [comment]
It runs for me now, but I get an error with the report:

```
/report.js:27
    table[serverName].perlBased = result;
                                ^

TypeError: Cannot set property 'perlBased' of undefined
    at processPerlBasedLine (/report.js:27:33)
    at processLine (/report.js:94:5)
    at Array.forEach (<anonymous>)
    at Socket.<anonymous> (/report.js:124:11)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:271:13)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by michielbdejong** [comment]
Yes, that's what I see as well, you should be able to fix that in https://github.com/solid/test-suite/blob/master/reporters/table/report.js#L18

**Comment by michielbdejong** [comment]
The output now looks like this:
```sh
tests/basic.t ...... 
Dubious, test returned 3 (wstat 768, 0x300)
Failed 3/8 subtests 
	(less 2 skipped subtests: 3 okay)
tests/httplists.t .. 
All 1 subtests passed 

Test Summary Report
-------------------
tests/basic.t    (Wstat: 768 Tests: 8 Failed: 3)
  Failed tests:  3-4, 8
  Non-zero exit status: 3
tests/httplists.t (Wstat: 0 Tests: 1 Failed: 0)
  Parse errors: More than one plan found in TAP output
Files=2, Tests=9,  2 wallclock secs ( 0.02 usr  0.00 sys +  2.14 cusr  0.22 csys =  2.38 CPU)
Result: FAIL
```

Previously it looked like this:
```sh
tests/basic.t .. 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/6 subtests 
	(less 2 skipped subtests: 2 okay)

Test Summary Report
-------------------
tests/basic.t (Wstat: 512 Tests: 6 Failed: 2)
  Failed tests:  1-2
  Non-zero exit status: 2
Files=1, Tests=6,  2 wallclock secs ( 0.00 usr  0.02 sys +  0.77 cusr  0.12 csys =  0.91 CPU)
Result: FAIL
```

**Comment by kjetilk** [comment]
Hmmm, I hadn't noticed the parse error warning there. I should look into that first. 

Also, @konobi, do you know any better ways to find the total number of passed tests and total number of tests, than adapt this script to parse that output?

**Comment by michielbdejong** [comment]
@kjetilk you can just update https://github.com/solid/test-suite/blob/master/reporters/table/report.js#L18-L46 until it works

**Comment by michielbdejong** [comment]
That script can also be run on the host machine while debugging, no need to rebuild that docker image each time you try out a change.

**Pull request merged**
