### PR TITLE
Remove the basic tests

### LINKED ISSUE #69: Fix or remove basic rdf-fixtures tests
I submitted a PR to https://github.com/kjetilk/p5-web-solid-test-basic/pull/9 to fix the basic rdf-fixtures tests, but according to @kjetilk it's better to remove those tests rather than fix them.

### PR DESCRIPTION
**Pull request by kjetilk**
The tests with value in the basic tests was the test comparing HEAD and GET headers, but as it was somewhat arbitrarily thrown together, I figured it is better to open a separate issue (#92) to do it properly later, and delete the whole basic tests for now. 

Merging this fixes #69 

It also closes https://github.com/kjetilk/p5-web-solid-test-basic/pull/9 as this is covered better in other tests.

### CODE REVIEW

**Comment by michielbdejong** [comment]
Let me know if you need help running the test suite on your laptop and/or on Travis.

**Comment by kjetilk** [comment]
> Please also update the "final output should look something like" section in https://github.com/solid/test-suite#test-suite-summary-in-docker

Oh, but the LDP Basic tests are different from these basic tests. :-) There's a separate issue for that in #83 .

**Comment by michielbdejong** [comment]
Right, but they are 6 out of 49 tests in the "RDF-fixtures" column right?
So those numbers will change?

**Comment by kjetilk** [comment]
Those numbers will certainly change. But I'll put that in after #90 .

The LDP basics is in #94 . Would be great to chat about running the Docker stuff now, because it errors for me.

**Pull request merged**
