### PR TITLE
Link to Java/Karate framework for ACP tests

### PR DESCRIPTION
**Pull request by michielbdejong**
@edwardsph what do you think?

### CODE REVIEW

**Review by emmettownsend — COMMENTED** [review]
ACP is not experimental. It is a proposal to the Authorization panel under review and the specification text is currently being written along with the primer. 
One Solid server, ESS already provides an implementation. An implementation for CSS is underway.

The conformance-test-harness repo contains the code for the test harness that has been described in a blog post, on a call and in the repo itself. This is open source, available for anybody to use and open to contributions from the community.  
In that repo there are examples of tests as they would be written in Karate, and the corresponding tests written for Jest. 
In order to ensure we get all of the benefits explained in the blog post we will be providing test cases for any of the specifications that we implement in ESS. They will also be used by CSS. 
Again for the test cases, anybody is free to use them and to contribute to them. We will be ensuring that the test cases are reviewed and formally signed off by the relevant members of the specification team. This should be an easier process as the test cases will be high level and declarative. 
You are correct that Pete is leading on the test harness project but he wont be alone in Inrupt, and will hopefully also be joined by members of the community. We will also have more people involved in creating the test cases.

**Comment by michielbdejong** [comment]
> we will be providing test cases for any of the specifications that we implement in ESS. They will also be used by CSS.

Please don't do this Emmet. I am begging you. It's not good for Solid as a whole in general if one of the companies from the eco-system attacks our independent test suite. Granted, Inrupt is a particularly big company and obviously a great benefactor of Solid, contributing many resources and engineer hours to the improvement of Solid. But that doesn't give you the right to behave this way. The meeting that Sarven called on Monday, where we were all present, and the proposed plan to move forward, which Yvo subsequently posted in https://gitter.im/solid/test-suite?at=603cf692120cd84f78e81d76, were our last attempt to de-escalate the situation.

I'm begging you one last time, please back down, please, let's merge this proposal, so that Pete can work on the ACP tests, using whichever programming language and DSL and framework he prefers, and we don't question the validity of our existing WebID-provider, CRUD, and WAC tests.

**Comment by edwardsph** [comment]
It is quite likely we will add some more example test cases (alongside the ones that already exist) to show how people could create ACP tests whilst we also look at other capabilities the harness needs to provide. However our priorities at the moment include work on the architecture of the whole harness, the test description documents and the reporting elements.

**Comment by michielbdejong** [comment]
By all means, work on your framework and use it in your own development cycle internally. 

Just don't compete with the *EXISTING* independent Solid test suite for WebID, CRUD, and WAC. So don't publish the results of your internal tests as some sort of "competing truth" about which server correctly implements the spec.

We already have the results for 4 out of 5 implementations (TrinPod coming soon), and I've been told engineers are working as we speak to fix the last few failing tests in their respective servers, so all servers will soon be 100% green on WebID, CRUD and WAC. Don't ruin that, please.

This PR is to propose that we use your framework for the ACP tests *ONLY*. There is no competition there, because ACP is not covered yet and I don't think any other panel members are writing them yet, so that's a win-win.

There, Inrupt could really contribute to the Solid test suite!

> We will be ensuring that the test cases are reviewed and formally signed off by the relevant members of the specification team.

I understand your best intentions, but please don't give them more work. They're already swamped and unable to attend to https://github.com/solid/solid-crud-tests/issues/46 and https://github.com/solid/web-access-control-tests/issues/34 as (understandably!) @csarven told me yesterday. Adding a competing test suite and more lists of disputed tests will only bog us down further. We need to one day arrive at a spec with zero disputed issues, where all servers behave in the same way, and all servers pass the same test suite.

Let's focus on what we have, improve it, add your ACP tests to it, and try to keep working peacefully alongside each other! <3

**Comment by csarven** [comment]
>swamped and unable to attend

The disputes you've put together are really useful, and thanks again for that work! I would like to get a chance to respond. Part of that requires us to process the available information and write things up.

I'd also like to better understand the type and causes of disputes eg. are there different interpretations (or preferences) on functionality and why? can we verify the test results? How can we improve from here?

**Comment by timbl** [comment]
@michielbdejong The work you’re doing in the independent test suite is valuable to both specification editors and server implementers alike.   You’ve requested I intervene.

In that regard, I’d like to make clear that neither I, the Spec Editors, nor the Solid Admin team have endorsed or designated any “Official test suite” or set of test suites for the Solid Specification. While such guidance certainly may occur in the future, at this time no such decision has been made.

It’s an open community and positive contributions from all parties are welcome. That is why it is a valuable and positive thing for the ecosystem to encourage broad test suite development and innovation.  At the moment, there are two test suites for Solid.

Just as how multiple server implementations help to inform and fill in gaps in the specification, multiple test suites help uncover ambiguities in the specification that otherwise go undetected or have defaulted to the interpretation of one suite. A difference in test results can serve to highlight clarifications needed in the spec or bugs in a test suite. 

While it’s possible that test suites sometimes consolidate or merge, I expect server implementations want to run against multiple test suites to ensure spec compliance and interoperability (especially where parts of the spec are in draft and being finalized). 

I hope this explains why we will move forward better together with test suites coexisting to provide even more value to the Solid ecosystem. 

Thanks

**Comment by michielbdejong** [comment]
OK, I can see the point in that. So we'll just have multiple overlapping test suites then, and only the spec itself will be unique. Thanks!

**Pull request closed without merging**
